# Generated by Django 4.2.13 on 2024-07-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHunterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='exp',
        ),
    ]
