# Generated by Django 4.2.13 on 2024-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHunterApp', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='HeadHunterApp.resume'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='HeadHunterApp.vacancy'),
        ),
    ]
